name = "mediorderpro"
compatibility_date = "2024-01-01"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = ".vercel/output/static"

[vars]
NEXT_PUBLIC_SUPABASE_URL = "https://xgcuzrrkwpthiqfcfwwd.supabase.co"
NEXT_PUBLIC_APP_URL = "https://med.albunyad.cloud"
